### ISSUE TITLE
Resource don't work with @falcon.before decorator

### ISSUE THREAD

**Issue by ogonbat** [Bogdanp/falcon_sugar#1]
Hi

this is the code
```python
class TestAuthResource(Resource):
    
    @falcon.before(authenticate(True))
    def on_get(self, req, resp):
        """Handles GET requests"""
        print("pass")
        return {'message': 'authentication work'}
```

and this is the authenticate function
```python
def authenticate(val=False):
    def hook(req, resp, resource, params):
        if val is True:
            token = req.get_header('Authorization')
            try:
                payload = jwt.decode(token, JWT_SECRET, algorithms=[JWT_ALGORITHM])
            except (jwt.DecodeError, jwt.ExpiredSignatureError):
                description = ('Please provide a valid auth token '
                               'as part of the request.')
                raise falcon.HTTPUnauthorized('Auth token not valid', description)

            if not _token_is_valid(payload['email']):
                description = ('The provided auth token is not valid. '
                               'Please request a new token and try again.')
                raise falcon.HTTPUnauthorized('User not valid', description)

    return hook
```

authenticate is quite simple, take the authorization header and check if is correct or not
if not raise an error if yes, at the moment do nothing

when i test the get method
the print return "pass", so is confirmed that is routed to the get method but the header is a 204, no content, so the Resource method don't take the return

thanks in advance

**Comment by Bogdanp** [comment]
I think this is caused by https://github.com/falconry/falcon/blob/73731948e961dbc18dd734b397302a82217e2b3c/falcon/hooks.py#L216-L221 as it doesn't return the result of the handler. Without updating that function, I don't think `falcon_sugar` can support the standard `@before` decorator.

**Comment by ogonbat** [comment]
Ok, i think you have to update the documentation with some constraints :-)
in your opinion is only for @before hook?

**Comment by Bogdanp** [comment]
Looking at the code, it likely affects the `@after` hook as well. I'll add a note to the readme about this.
